# Site settings
title: Traveling Ruby
email: info@phusion.nl
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

exclude:
  - foo
  - osx
  - linux
  - '*.tar.gz'
