name: MacOS arm64
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  make-osx-arm64:
    strategy:
      matrix:
        os: [self-hosted]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
            # rbenv local system
            # sudo gem install bundler:2.3.17
            rbenv global 3.0.5
      - name: build arm64
        run: |
            cd osx
            rake stash_conflicting_paths
            rake --trace
            rake unstash_conflicting_paths
            ls
        env:
          DEVELOPER_DIR: /Library/Developer/CommandLineTools
          CC: /Users/admin/foo/actions-runner/_work/traveling-ruby/traveling-ruby/osx/internal/bin/cc
      - name: 'Upload Artifact- osx arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230508-3.2.2-osx-arm64.tar.gz
          path: osx/traveling-ruby-20230508-3.2.2-osx-arm64.tar.gz