name: MacOS x86_64 - self hosted
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  make-osx-x86_64:
    strategy:
      matrix:
        os: [self-hosted]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: |
            # rbenv local system
            # sudo gem install bundler:2.3.17
            rbenv global 3.0.5
            # softwareupdate --install-rosetta --agree-to-license
      - name: build x86_64
        run: |
            # env /usr/bin/arch -x86_64 /bin/bash
            uname -m
            cd osx
            rake stash_conflicting_paths
            rake --trace
            rake unstash_conflicting_paths
            ls
        env:
          DEVELOPER_DIR: /Library/Developer/CommandLineTools
          CC: /Users/admin/foo/actions-runner/_work/traveling-ruby/traveling-ruby/osx/internal/bin/cc
      - name: 'Upload Artifact- osx x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230504-3.1.2-osx-x86_64.tar.gz
          path: osx/traveling-ruby-20230504-3.1.2-osx-x86_64.tar.gz