name: MacOS x86_64
on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  make-osx-x86_64:
    strategy:
      matrix:
        os: [macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      # - run: |
      #     brew install ruby@2.6
      #     brew install rbenv
      #     rbenv versions
      #     ruby --version
      #     rbenv global 3.1.2
      #     gem install bundler:2.3.17
      #     rbenv install 3.1.2
      #     ls /Library/Ruby/Gems/2.6.0/gems/
      # - name: "Set up Ruby"
      #   uses: ruby/setup-ruby@v1
      #   with:
      #       ruby-version: 3.1.2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
            xcode-version: '14.2'
      # - name: 
      #   run: |
      #       curl -LO https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX10.14.sdk.tar.xz
      #       echo $(xcode-select -p)
      #       echo $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs
      #       sudo tar -xf MacOSX10.14.sdk.tar.xz -C "$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs"
      - name: build x86
        run: |
            # gem install bundler:2.3.17
            cd osx
            rake stash_conflicting_paths
            rake --trace
            rake unstash_conflicting_paths
            ls
        env:
          DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
      - name: 'Upload Artifact- osx x86_64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230504-3.1.2-osx-x86_64.tar.gz
          path: osx/traveling-ruby-20230504-3.1.2-osx-x86_64.tar.gz