name: Linux - x86_64 - image builder
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  make-ubuntu-x86_64-image:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: 3.1.2
      - name: package
        run: |
          docker run --privileged --rm tonistiigi/binfmt --install all
          cd linux
          rake image
          docker images
        env:
          ARCHITECTURES: "x86_64"