name: Linux - arm64 - build from dockerhub builder
# Broken on GitHub Actions with QEMU
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  PKG_DATE: 20240205

jobs:
  make-ubuntu-arm64:
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby-version: [2.6.10, 3.0.4, 3.1.4, 3.2.3, 3.3.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.11.0
      #   with:
      #     all_but_latest: true
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: ${{ matrix.ruby-version }}
      - name: package
        run: |
            docker run --privileged --rm tonistiigi/binfmt --install all
            cd linux
            rake
            ls
        env:
          ARCHITECTURES: "arm64"
          RUBY_VERSIONS: ${{ matrix.ruby-version }}
      - name: package gems
        run: ./scripts/package-gems.sh     
        env:
          PLATFORM: linux
      - name: 'Upload Artifact - linux arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-linux-arm64.tar.gz
          path: linux/traveling-ruby*.tar.gz
      - name: test
        run: |
            cd linux
            rake test_docker
        env:
          ARCHITECTURES: "arm64"
          RUBY_VERSIONS: ${{ matrix.ruby-version }}