name: Linux - arm64 - build from dockerhub builder
on:
  push:
    branches: [ main, ci ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.circleci/**'
      - '.cirrus.yml'

jobs:
  make-ubuntu-arm64:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: 3.2.2
      - name: package
        run: |
            docker run --privileged --rm tonistiigi/binfmt --install all
            cd linux
            rake
            ls
        env:
          ARCHITECTURES: "arm64"
      - name: 'Upload Artifact - linux arm64'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230508-3.2.2-linux-arm64.tar.gz
          path: linux/traveling-ruby-20230508-3.2.2-linux-arm64.tar.gz