name: Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  make-windows:
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: 3.1.2
      - name: 
        run: |
            cd windows
            sh -c 'mkdir -p cache output/3.1.2'
            sh -c './build-ruby -a x86_64 -r 3.1.2 cache output/3.1.2'
            sh -c './package -r traveling-ruby-20230504-3.1.2-x86_64-win32.tar.gz output/3.1.2'
            sh -c 'ls'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-20230504-3.1.2-x86_64-win32.tar.gz
          path: windows/traveling-ruby-20230504-3.1.2-x86_64-win32.tar.gz
