name: Windows
on:
  push:
    branches: [ main, ci ]
  pull_request:
    branches: [ main, ci ]

env:
  RB_VERSION: 3.2.2
  PKG_DATE: 20230508

jobs:
  make-windows:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86_64,x86]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:      
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: ${{ env.RB_VERSION }}
      - name: package ${{ matrix.arch }}
        run: |
          uname -m
          cd windows
          sh -c 'mkdir -p cache output/${{ env.RB_VERSION }}'
          sh -c './build-ruby -a ${{ matrix.arch }} -r ${{ env.RB_VERSION }} cache output/${{ env.RB_VERSION }}'
          sh -c './package -r traveling-ruby-${{ env.PKG_DATE }}-${{ env.RB_VERSION }}-${{ matrix.arch }}-windows.tar.gz output/${{ env.RB_VERSION }}'
          sh -c 'ls'
      - name: 'Upload Artifact - traveling-ruby-${{ env.PKG_DATE }}-${{ env.RB_VERSION }}-${{ matrix.arch }}-windows'
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-${{ env.PKG_DATE }}-${{ env.RB_VERSION }}-${{ matrix.arch }}-windows.tar.gz
          path: windows/traveling-ruby-${{ env.PKG_DATE }}-${{ env.RB_VERSION }}-${{ matrix.arch }}-windows.tar.gz
