name: Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PKG_DATE: 20240205

jobs:
  make-windows:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x86_64, x86]
        ruby-version: [2.6.10, 2.7.8, 3.0.6, 3.1.4, 3.2.3, 3.3.0]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      # - name: Cancel Previous Runs
      #   uses: styfle/cancel-workflow-action@0.11.0
      #   with:
      #     all_but_latest: true
      - uses: actions/checkout@v3
      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: package ${{ matrix.arch }}
        run: |
          uname -m
          cd windows
          sh -c 'mkdir -p cache output/${{ matrix.ruby-version }}'
          sh -c './build-ruby.sh -a ${{ matrix.arch }} -r ${{ matrix.ruby-version }} cache output/${{ matrix.ruby-version }}'
          sh -c './package.sh -r traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-${{ matrix.arch }}-windows.tar.gz output/${{ matrix.ruby-version }}'
          sh -c 'ls'
      - name: "Upload Artifact - traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-${{ matrix.arch }}-windows"
        uses: actions/upload-artifact@v3
        with:
          name: traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-${{ matrix.arch }}-windows.tar.gz
          path: windows/traveling-ruby-${{ env.PKG_DATE }}-${{ matrix.ruby-version }}-${{ matrix.arch }}-windows.tar.gz
